"""empty message

Revision ID: ce3a4dafb1a4
Revises: 
Create Date: 2025-04-21 15:55:50.038233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3a4dafb1a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cuisine', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_open', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivers', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('delivers')
        batch_op.drop_column('is_open')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('rating')
        batch_op.drop_column('price')
        batch_op.drop_column('cuisine')
        batch_op.drop_column('address')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
